--  This spec has been automatically generated from STM32U073.svd

pragma Restrictions (No_Elaboration_Code);
pragma Ada_2012;
pragma Style_Checks (Off);

with HAL;
with System;

package STM32_SVD.VREFBUF is
   pragma Preelaborate;

   ---------------
   -- Registers --
   ---------------

   --  VREFBUF control and status register
   type VREFBUF_CSR_Register is record
      --  Voltage reference buffer mode enable This bit is used to enable the
      --  voltage reference buffer mode.
      ENVR          : Boolean := False;
      --  High impedance mode This bit controls the analog switch to connect or
      --  not the V<sub>REF+</sub> pin. Refer to Table172: VREF buffer modes
      --  for the mode descriptions depending on ENVR bit configuration.
      HIZ           : Boolean := True;
      --  Voltage reference scale This bit selects the value generated by the
      --  voltage reference buffer.
      VRS           : Boolean := False;
      --  Read-only. Voltage reference buffer ready
      VRR           : Boolean := False;
      --  unspecified
      Reserved_4_31 : HAL.UInt28 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for VREFBUF_CSR_Register use record
      ENVR          at 0 range 0 .. 0;
      HIZ           at 0 range 1 .. 1;
      VRS           at 0 range 2 .. 2;
      VRR           at 0 range 3 .. 3;
      Reserved_4_31 at 0 range 4 .. 31;
   end record;

   subtype VREFBUF_CCR_TRIM_Field is HAL.UInt6;

   --  VREFBUF calibration control register
   type VREFBUF_CCR_Register is record
      --  None
      TRIM          : VREFBUF_CCR_TRIM_Field := 16#0#;
      --  unspecified
      Reserved_6_31 : HAL.UInt26 := 16#0#;
   end record
     with Volatile_Full_Access, Object_Size => 32,
          Bit_Order => System.Low_Order_First;

   for VREFBUF_CCR_Register use record
      TRIM          at 0 range 0 .. 5;
      Reserved_6_31 at 0 range 6 .. 31;
   end record;

   -----------------
   -- Peripherals --
   -----------------

   --  VREFBUF address block description
   type VREFBUF_Peripheral is record
      --  VREFBUF control and status register
      VREFBUF_CSR : aliased VREFBUF_CSR_Register;
      --  VREFBUF calibration control register
      VREFBUF_CCR : aliased VREFBUF_CCR_Register;
   end record
     with Volatile;

   for VREFBUF_Peripheral use record
      VREFBUF_CSR at 16#0# range 0 .. 31;
      VREFBUF_CCR at 16#4# range 0 .. 31;
   end record;

   --  VREFBUF address block description
   VREFBUF_Periph : aliased VREFBUF_Peripheral
     with Import, Address => VREFBUF_Base;

end STM32_SVD.VREFBUF;
