--  Copyright 2016-2019 NXP
--  All rights reserved.SPDX-License-Identifier: BSD-3-Clause


--  This spec has been automatically generated from LPC55S6x.svd

pragma Restrictions (No_Elaboration_Code);
pragma Ada_2012;
pragma Style_Checks (Off);

with HAL;
with System;

package NXP_SVD.USBFSH is
   pragma Preelaborate;

   ---------------
   -- Registers --
   ---------------

   subtype HCREVISION_REV_Field is HAL.UInt8;

   --  BCD representation of the version of the HCI specification that is
   --  implemented by the Host Controller (HC)
   type HCREVISION_Register is record
      --  Read-only. Revision.
      REV           : HCREVISION_REV_Field;
      --  unspecified
      Reserved_8_31 : HAL.UInt24;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCREVISION_Register use record
      REV           at 0 range 0 .. 7;
      Reserved_8_31 at 0 range 8 .. 31;
   end record;

   subtype HCCONTROL_CBSR_Field is HAL.UInt2;
   subtype HCCONTROL_HCFS_Field is HAL.UInt2;

   --  Defines the operating modes of the HC
   type HCCONTROL_Register is record
      --  ControlBulkServiceRatio.
      CBSR           : HCCONTROL_CBSR_Field := 16#0#;
      --  PeriodicListEnable.
      PLE            : Boolean := False;
      --  IsochronousEnable.
      IE             : Boolean := False;
      --  ControlListEnable.
      CLE            : Boolean := False;
      --  BulkListEnable This bit is set to enable the processing of the Bulk
      --  list in the next Frame.
      BLE            : Boolean := False;
      --  HostControllerFunctionalState for USB 00b: USBRESET 01b: USBRESUME
      --  10b: USBOPERATIONAL 11b: USBSUSPEND A transition to USBOPERATIONAL
      --  from another state causes SOFgeneration to begin 1 ms later.
      HCFS           : HCCONTROL_HCFS_Field := 16#0#;
      --  InterruptRouting This bit determines the routing of interrupts
      --  generated by events registered in HcInterruptStatus.
      IR             : Boolean := False;
      --  RemoteWakeupConnected This bit indicates whether HC supports remote
      --  wake-up signaling.
      RWC            : Boolean := False;
      --  RemoteWakeupEnable This bit is used by HCD to enable or disable the
      --  remote wake-up feature upon the detection of upstream resume
      --  signaling.
      RWE            : Boolean := False;
      --  unspecified
      Reserved_11_31 : HAL.UInt21 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCCONTROL_Register use record
      CBSR           at 0 range 0 .. 1;
      PLE            at 0 range 2 .. 2;
      IE             at 0 range 3 .. 3;
      CLE            at 0 range 4 .. 4;
      BLE            at 0 range 5 .. 5;
      HCFS           at 0 range 6 .. 7;
      IR             at 0 range 8 .. 8;
      RWC            at 0 range 9 .. 9;
      RWE            at 0 range 10 .. 10;
      Reserved_11_31 at 0 range 11 .. 31;
   end record;

   subtype HCCOMMANDSTATUS_SOC_Field is HAL.UInt2;

   --  This register is used to receive the commands from the Host Controller
   --  Driver (HCD)
   type HCCOMMANDSTATUS_Register is record
      --  HostControllerReset This bit is set by HCD to initiate a software
      --  reset of HC.
      HCR           : Boolean := False;
      --  ControlListFilled This bit is used to indicate whether there are any
      --  TDs on the Control list.
      CLF           : Boolean := False;
      --  BulkListFilled This bit is used to indicate whether there are any TDs
      --  on the Bulk list.
      BLF           : Boolean := False;
      --  OwnershipChangeRequest This bit is set by an OS HCD to request a
      --  change of control of the HC.
      OCR           : Boolean := False;
      --  unspecified
      Reserved_4_5  : HAL.UInt2 := 16#0#;
      --  SchedulingOverrunCount These bits are incremented on each scheduling
      --  overrun error.
      SOC           : HCCOMMANDSTATUS_SOC_Field := 16#0#;
      --  unspecified
      Reserved_8_31 : HAL.UInt24 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCCOMMANDSTATUS_Register use record
      HCR           at 0 range 0 .. 0;
      CLF           at 0 range 1 .. 1;
      BLF           at 0 range 2 .. 2;
      OCR           at 0 range 3 .. 3;
      Reserved_4_5  at 0 range 4 .. 5;
      SOC           at 0 range 6 .. 7;
      Reserved_8_31 at 0 range 8 .. 31;
   end record;

   subtype HCINTERRUPTSTATUS_OC_Field is HAL.UInt22;

   --  Indicates the status on various events that cause hardware interrupts by
   --  setting the appropriate bits
   type HCINTERRUPTSTATUS_Register is record
      --  SchedulingOverrun This bit is set when the USB schedule for the
      --  current Frame overruns and after the update of HccaFrameNumber.
      SO           : Boolean := False;
      --  WritebackDoneHead This bit is set immediately after HC has written
      --  HcDoneHead to HccaDoneHead.
      WDH          : Boolean := False;
      --  StartofFrame This bit is set by HC at each start of a frame and after
      --  the update of HccaFrameNumber.
      SF           : Boolean := False;
      --  ResumeDetected This bit is set when HC detects that a device on the
      --  USB is asserting resume signaling.
      RD           : Boolean := False;
      --  UnrecoverableError This bit is set when HC detects a system error not
      --  related to USB.
      UE           : Boolean := False;
      --  FrameNumberOverflow This bit is set when the MSb of HcFmNumber (bit
      --  15) changes value, from 0 to 1 or from 1 to 0, and after
      --  HccaFrameNumber has been updated.
      FNO          : Boolean := False;
      --  RootHubStatusChange This bit is set when the content of HcRhStatus or
      --  the content of any of HcRhPortStatus[NumberofDownstreamPort] has
      --  changed.
      RHSC         : Boolean := False;
      --  unspecified
      Reserved_7_9 : HAL.UInt3 := 16#0#;
      --  OwnershipChange This bit is set by HC when HCD sets the
      --  OwnershipChangeRequest field in HcCommandStatus.
      OC           : HCINTERRUPTSTATUS_OC_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCINTERRUPTSTATUS_Register use record
      SO           at 0 range 0 .. 0;
      WDH          at 0 range 1 .. 1;
      SF           at 0 range 2 .. 2;
      RD           at 0 range 3 .. 3;
      UE           at 0 range 4 .. 4;
      FNO          at 0 range 5 .. 5;
      RHSC         at 0 range 6 .. 6;
      Reserved_7_9 at 0 range 7 .. 9;
      OC           at 0 range 10 .. 31;
   end record;

   --  Controls the bits in the HcInterruptStatus register and indicates which
   --  events will generate a hardware interrupt
   type HCINTERRUPTENABLE_Register is record
      --  Scheduling Overrun interrupt.
      SO            : Boolean := False;
      --  HcDoneHead Writeback interrupt.
      WDH           : Boolean := False;
      --  Start of Frame interrupt.
      SF            : Boolean := False;
      --  Resume Detect interrupt.
      RD            : Boolean := False;
      --  Unrecoverable Error interrupt.
      UE            : Boolean := False;
      --  Frame Number Overflow interrupt.
      FNO           : Boolean := False;
      --  Root Hub Status Change interrupt.
      RHSC          : Boolean := False;
      --  unspecified
      Reserved_7_29 : HAL.UInt23 := 16#0#;
      --  Ownership Change interrupt.
      OC            : Boolean := False;
      --  Master Interrupt Enable.
      MIE           : Boolean := False;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCINTERRUPTENABLE_Register use record
      SO            at 0 range 0 .. 0;
      WDH           at 0 range 1 .. 1;
      SF            at 0 range 2 .. 2;
      RD            at 0 range 3 .. 3;
      UE            at 0 range 4 .. 4;
      FNO           at 0 range 5 .. 5;
      RHSC          at 0 range 6 .. 6;
      Reserved_7_29 at 0 range 7 .. 29;
      OC            at 0 range 30 .. 30;
      MIE           at 0 range 31 .. 31;
   end record;

   --  The bits in this register are used to disable corresponding bits in the
   --  HCInterruptStatus register and in turn disable that event leading to
   --  hardware interrupt
   type HCINTERRUPTDISABLE_Register is record
      --  Scheduling Overrun interrupt.
      SO            : Boolean := False;
      --  HcDoneHead Writeback interrupt.
      WDH           : Boolean := False;
      --  Start of Frame interrupt.
      SF            : Boolean := False;
      --  Resume Detect interrupt.
      RD            : Boolean := False;
      --  Unrecoverable Error interrupt.
      UE            : Boolean := False;
      --  Frame Number Overflow interrupt.
      FNO           : Boolean := False;
      --  Root Hub Status Change interrupt.
      RHSC          : Boolean := False;
      --  unspecified
      Reserved_7_29 : HAL.UInt23 := 16#0#;
      --  Ownership Change interrupt.
      OC            : Boolean := False;
      --  A 0 written to this field is ignored by HC.
      MIE           : Boolean := False;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCINTERRUPTDISABLE_Register use record
      SO            at 0 range 0 .. 0;
      WDH           at 0 range 1 .. 1;
      SF            at 0 range 2 .. 2;
      RD            at 0 range 3 .. 3;
      UE            at 0 range 4 .. 4;
      FNO           at 0 range 5 .. 5;
      RHSC          at 0 range 6 .. 6;
      Reserved_7_29 at 0 range 7 .. 29;
      OC            at 0 range 30 .. 30;
      MIE           at 0 range 31 .. 31;
   end record;

   subtype HCHCCA_HCCA_Field is HAL.UInt24;

   --  Contains the physical address of the host controller communication area
   type HCHCCA_Register is record
      --  unspecified
      Reserved_0_7 : HAL.UInt8 := 16#0#;
      --  Base address of the Host Controller Communication Area.
      HCCA         : HCHCCA_HCCA_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCHCCA_Register use record
      Reserved_0_7 at 0 range 0 .. 7;
      HCCA         at 0 range 8 .. 31;
   end record;

   subtype HCPERIODCURRENTED_PCED_Field is HAL.UInt28;

   --  Contains the physical address of the current isochronous or interrupt
   --  endpoint descriptor
   type HCPERIODCURRENTED_Register is record
      --  unspecified
      Reserved_0_3 : HAL.UInt4;
      --  Read-only. The content of this register is updated by HC after a
      --  periodic ED is processed.
      PCED         : HCPERIODCURRENTED_PCED_Field;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCPERIODCURRENTED_Register use record
      Reserved_0_3 at 0 range 0 .. 3;
      PCED         at 0 range 4 .. 31;
   end record;

   subtype HCCONTROLHEADED_CHED_Field is HAL.UInt28;

   --  Contains the physical address of the first endpoint descriptor of the
   --  control list
   type HCCONTROLHEADED_Register is record
      --  unspecified
      Reserved_0_3 : HAL.UInt4 := 16#0#;
      --  HC traverses the Control list starting with the HcControlHeadED
      --  pointer.
      CHED         : HCCONTROLHEADED_CHED_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCCONTROLHEADED_Register use record
      Reserved_0_3 at 0 range 0 .. 3;
      CHED         at 0 range 4 .. 31;
   end record;

   subtype HCCONTROLCURRENTED_CCED_Field is HAL.UInt28;

   --  Contains the physical address of the current endpoint descriptor of the
   --  control list
   type HCCONTROLCURRENTED_Register is record
      --  unspecified
      Reserved_0_3 : HAL.UInt4 := 16#0#;
      --  ControlCurrentED.
      CCED         : HCCONTROLCURRENTED_CCED_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCCONTROLCURRENTED_Register use record
      Reserved_0_3 at 0 range 0 .. 3;
      CCED         at 0 range 4 .. 31;
   end record;

   subtype HCBULKHEADED_BHED_Field is HAL.UInt28;

   --  Contains the physical address of the first endpoint descriptor of the
   --  bulk list
   type HCBULKHEADED_Register is record
      --  unspecified
      Reserved_0_3 : HAL.UInt4 := 16#0#;
      --  BulkHeadED HC traverses the bulk list starting with the HcBulkHeadED
      --  pointer.
      BHED         : HCBULKHEADED_BHED_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCBULKHEADED_Register use record
      Reserved_0_3 at 0 range 0 .. 3;
      BHED         at 0 range 4 .. 31;
   end record;

   subtype HCBULKCURRENTED_BCED_Field is HAL.UInt28;

   --  Contains the physical address of the current endpoint descriptor of the
   --  bulk list
   type HCBULKCURRENTED_Register is record
      --  unspecified
      Reserved_0_3 : HAL.UInt4 := 16#0#;
      --  BulkCurrentED This is advanced to the next ED after the HC has served
      --  the current one.
      BCED         : HCBULKCURRENTED_BCED_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCBULKCURRENTED_Register use record
      Reserved_0_3 at 0 range 0 .. 3;
      BCED         at 0 range 4 .. 31;
   end record;

   subtype HCDONEHEAD_DH_Field is HAL.UInt28;

   --  Contains the physical address of the last transfer descriptor added to
   --  the 'Done' queue
   type HCDONEHEAD_Register is record
      --  unspecified
      Reserved_0_3 : HAL.UInt4;
      --  Read-only. DoneHead When a TD is completed, HC writes the content of
      --  HcDoneHead to the NextTD field of the TD.
      DH           : HCDONEHEAD_DH_Field;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCDONEHEAD_Register use record
      Reserved_0_3 at 0 range 0 .. 3;
      DH           at 0 range 4 .. 31;
   end record;

   subtype HCFMINTERVAL_FI_Field is HAL.UInt14;
   subtype HCFMINTERVAL_FSMPS_Field is HAL.UInt15;

   --  Defines the bit time interval in a frame and the full speed maximum
   --  packet size which would not cause an overrun
   type HCFMINTERVAL_Register is record
      --  FrameInterval This specifies the interval between two consecutive
      --  SOFs in bit times.
      FI             : HCFMINTERVAL_FI_Field := 16#2EDF#;
      --  unspecified
      Reserved_14_15 : HAL.UInt2 := 16#0#;
      --  FSLargestDataPacket This field specifies a value which is loaded into
      --  the Largest Data Packet Counter at the beginning of each frame.
      FSMPS          : HCFMINTERVAL_FSMPS_Field := 16#0#;
      --  FrameIntervalToggle HCD toggles this bit whenever it loads a new
      --  value to FrameInterval.
      FIT            : Boolean := False;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCFMINTERVAL_Register use record
      FI             at 0 range 0 .. 13;
      Reserved_14_15 at 0 range 14 .. 15;
      FSMPS          at 0 range 16 .. 30;
      FIT            at 0 range 31 .. 31;
   end record;

   subtype HCFMREMAINING_FR_Field is HAL.UInt14;

   --  A 14-bit counter showing the bit time remaining in the current frame
   type HCFMREMAINING_Register is record
      --  Read-only. FrameRemaining This counter is decremented at each bit
      --  time.
      FR             : HCFMREMAINING_FR_Field;
      --  unspecified
      Reserved_14_30 : HAL.UInt17;
      --  Read-only. FrameRemainingToggle This bit is loaded from the
      --  FrameIntervalToggle field of HcFmInterval whenever FrameRemaining
      --  reaches 0.
      FRT            : Boolean;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCFMREMAINING_Register use record
      FR             at 0 range 0 .. 13;
      Reserved_14_30 at 0 range 14 .. 30;
      FRT            at 0 range 31 .. 31;
   end record;

   subtype HCFMNUMBER_FN_Field is HAL.UInt16;

   --  Contains a 16-bit counter and provides the timing reference among events
   --  happening in the HC and the HCD
   type HCFMNUMBER_Register is record
      --  Read-only. FrameNumber This is incremented when HcFmRemaining is
      --  re-loaded.
      FN             : HCFMNUMBER_FN_Field;
      --  unspecified
      Reserved_16_31 : HAL.UInt16;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCFMNUMBER_Register use record
      FN             at 0 range 0 .. 15;
      Reserved_16_31 at 0 range 16 .. 31;
   end record;

   subtype HCPERIODICSTART_PS_Field is HAL.UInt14;

   --  Contains a programmable 14-bit value which determines the earliest time
   --  HC should start processing a periodic list
   type HCPERIODICSTART_Register is record
      --  PeriodicStart After a hardware reset, this field is cleared and then
      --  set by HCD during the HC initialization.
      PS             : HCPERIODICSTART_PS_Field := 16#0#;
      --  unspecified
      Reserved_14_31 : HAL.UInt18 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCPERIODICSTART_Register use record
      PS             at 0 range 0 .. 13;
      Reserved_14_31 at 0 range 14 .. 31;
   end record;

   subtype HCLSTHRESHOLD_LST_Field is HAL.UInt12;

   --  Contains 11-bit value which is used by the HC to determine whether to
   --  commit to transfer a maximum of 8-byte LS packet before EOF
   type HCLSTHRESHOLD_Register is record
      --  LSThreshold This field contains a value which is compared to the
      --  FrameRemaining field prior to initiating a Low Speed transaction.
      LST            : HCLSTHRESHOLD_LST_Field := 16#628#;
      --  unspecified
      Reserved_12_31 : HAL.UInt20 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCLSTHRESHOLD_Register use record
      LST            at 0 range 0 .. 11;
      Reserved_12_31 at 0 range 12 .. 31;
   end record;

   subtype HCRHDESCRIPTORA_NDP_Field is HAL.UInt8;
   subtype HCRHDESCRIPTORA_POTPGT_Field is HAL.UInt8;

   --  First of the two registers which describes the characteristics of the
   --  root hub
   type HCRHDESCRIPTORA_Register is record
      --  NumberDownstreamPorts These bits specify the number of downstream
      --  ports supported by the root hub.
      NDP            : HCRHDESCRIPTORA_NDP_Field := 16#2#;
      --  PowerSwitchingMode This bit is used to specify how the power
      --  switching of the root hub ports is controlled.
      PSM            : Boolean := True;
      --  NoPowerSwitching These bits are used to specify whether power
      --  switching is supported or port are always powered.
      NPS            : Boolean := False;
      --  DeviceType This bit specifies that the root hub is not a compound
      --  device.
      DT             : Boolean := False;
      --  OverCurrentProtectionMode This bit describes how the overcurrent
      --  status for the root hub ports are reported.
      OCPM           : Boolean := True;
      --  NoOverCurrentProtection This bit describes how the overcurrent status
      --  for the root hub ports are reported.
      NOCP           : Boolean := False;
      --  unspecified
      Reserved_13_23 : HAL.UInt11 := 16#0#;
      --  PowerOnToPowerGoodTime This byte specifies the duration the HCD has
      --  to wait before accessing a powered-on port of the root hub.
      POTPGT         : HCRHDESCRIPTORA_POTPGT_Field := 16#FF#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCRHDESCRIPTORA_Register use record
      NDP            at 0 range 0 .. 7;
      PSM            at 0 range 8 .. 8;
      NPS            at 0 range 9 .. 9;
      DT             at 0 range 10 .. 10;
      OCPM           at 0 range 11 .. 11;
      NOCP           at 0 range 12 .. 12;
      Reserved_13_23 at 0 range 13 .. 23;
      POTPGT         at 0 range 24 .. 31;
   end record;

   subtype HCRHDESCRIPTORB_DR_Field is HAL.UInt16;
   subtype HCRHDESCRIPTORB_PPCM_Field is HAL.UInt16;

   --  Second of the two registers which describes the characteristics of the
   --  Root Hub
   type HCRHDESCRIPTORB_Register is record
      --  DeviceRemovable Each bit is dedicated to a port of the Root Hub.
      DR   : HCRHDESCRIPTORB_DR_Field := 16#0#;
      --  PortPowerControlMask Each bit indicates if a port is affected by a
      --  global power control command when PowerSwitchingMode is set.
      PPCM : HCRHDESCRIPTORB_PPCM_Field := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCRHDESCRIPTORB_Register use record
      DR   at 0 range 0 .. 15;
      PPCM at 0 range 16 .. 31;
   end record;

   --  This register is divided into two parts
   type HCRHSTATUS_Register is record
      --  (read) LocalPowerStatus The Root Hub does not support the local power
      --  status feature; thus, this bit is always read as 0.
      LPS            : Boolean := False;
      --  OverCurrentIndicator This bit reports overcurrent conditions when the
      --  global reporting is implemented.
      OCI            : Boolean := False;
      --  unspecified
      Reserved_2_14  : HAL.UInt13 := 16#0#;
      --  (read) DeviceRemoteWakeupEnable This bit enables a
      --  ConnectStatusChange bit as a resume event, causing a USBSUSPEND to
      --  USBRESUME state transition and setting the ResumeDetected interrupt.
      DRWE           : Boolean := False;
      --  (read) LocalPowerStatusChange The root hub does not support the local
      --  power status feature.
      LPSC           : Boolean := False;
      --  OverCurrentIndicatorChange This bit is set by hardware when a change
      --  has occurred to the OCI field of this register.
      OCIC           : Boolean := False;
      --  unspecified
      Reserved_18_30 : HAL.UInt13 := 16#0#;
      --  (write) ClearRemoteWakeupEnable Writing a 1 clears
      --  DeviceRemoveWakeupEnable.
      CRWE           : Boolean := False;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCRHSTATUS_Register use record
      LPS            at 0 range 0 .. 0;
      OCI            at 0 range 1 .. 1;
      Reserved_2_14  at 0 range 2 .. 14;
      DRWE           at 0 range 15 .. 15;
      LPSC           at 0 range 16 .. 16;
      OCIC           at 0 range 17 .. 17;
      Reserved_18_30 at 0 range 18 .. 30;
      CRWE           at 0 range 31 .. 31;
   end record;

   --  Controls and reports the port events on a per-port basis
   type HCRHPORTSTATUS_Register is record
      --  (read) CurrentConnectStatus This bit reflects the current state of
      --  the downstream port.
      CCS            : Boolean := False;
      --  (read) PortEnableStatus This bit indicates whether the port is
      --  enabled or disabled.
      PES            : Boolean := False;
      --  (read) PortSuspendStatus This bit indicates the port is suspended or
      --  in the resume sequence.
      PSS            : Boolean := False;
      --  (read) PortOverCurrentIndicator This bit is only valid when the Root
      --  Hub is configured in such a way that overcurrent conditions are
      --  reported on a per-port basis.
      POCI           : Boolean := False;
      --  (read) PortResetStatus When this bit is set by a write to
      --  SetPortReset, port reset signaling is asserted.
      PRS            : Boolean := False;
      --  unspecified
      Reserved_5_7   : HAL.UInt3 := 16#0#;
      --  (read) PortPowerStatus This bit reflects the porta's power status,
      --  regardless of the type of power switching implemented.
      PPS            : Boolean := False;
      --  (read) LowSpeedDeviceAttached This bit indicates the speed of the
      --  device attached to this port.
      LSDA           : Boolean := False;
      --  unspecified
      Reserved_10_15 : HAL.UInt6 := 16#0#;
      --  ConnectStatusChange This bit is set whenever a connect or disconnect
      --  event occurs.
      CSC            : Boolean := False;
      --  PortEnableStatusChange This bit is set when hardware events cause the
      --  PortEnableStatus bit to be cleared.
      PESC           : Boolean := False;
      --  PortSuspendStatusChange This bit is set when the full resume sequence
      --  is completed.
      PSSC           : Boolean := False;
      --  PortOverCurrentIndicatorChange This bit is valid only if overcurrent
      --  conditions are reported on a per-port basis.
      OCIC           : Boolean := False;
      --  PortResetStatusChange This bit is set at the end of the 10 ms port
      --  reset signal.
      PRSC           : Boolean := False;
      --  unspecified
      Reserved_21_31 : HAL.UInt11 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for HCRHPORTSTATUS_Register use record
      CCS            at 0 range 0 .. 0;
      PES            at 0 range 1 .. 1;
      PSS            at 0 range 2 .. 2;
      POCI           at 0 range 3 .. 3;
      PRS            at 0 range 4 .. 4;
      Reserved_5_7   at 0 range 5 .. 7;
      PPS            at 0 range 8 .. 8;
      LSDA           at 0 range 9 .. 9;
      Reserved_10_15 at 0 range 10 .. 15;
      CSC            at 0 range 16 .. 16;
      PESC           at 0 range 17 .. 17;
      PSSC           at 0 range 18 .. 18;
      OCIC           at 0 range 19 .. 19;
      PRSC           at 0 range 20 .. 20;
      Reserved_21_31 at 0 range 21 .. 31;
   end record;

   --  Controls the port if it is attached to the host block or the device
   --  block
   type PORTMODE_Register is record
      --  Port ID pin value.
      ID             : Boolean := False;
      --  unspecified
      Reserved_1_7   : HAL.UInt7 := 16#0#;
      --  Port ID pin pull-up enable.
      ID_EN          : Boolean := False;
      --  unspecified
      Reserved_9_15  : HAL.UInt7 := 16#0#;
      --  1: device 0: host.
      DEV_ENABLE     : Boolean := False;
      --  unspecified
      Reserved_17_31 : HAL.UInt15 := 16#0#;
   end record
     with Volatile_Full_Access, Size => 32,
          Bit_Order => System.Low_Order_First;

   for PORTMODE_Register use record
      ID             at 0 range 0 .. 0;
      Reserved_1_7   at 0 range 1 .. 7;
      ID_EN          at 0 range 8 .. 8;
      Reserved_9_15  at 0 range 9 .. 15;
      DEV_ENABLE     at 0 range 16 .. 16;
      Reserved_17_31 at 0 range 17 .. 31;
   end record;

   -----------------
   -- Peripherals --
   -----------------

   --  USB0 Full-speed Host controller
   type USBFSH_Peripheral is record
      --  BCD representation of the version of the HCI specification that is
      --  implemented by the Host Controller (HC)
      HCREVISION         : aliased HCREVISION_Register;
      --  Defines the operating modes of the HC
      HCCONTROL          : aliased HCCONTROL_Register;
      --  This register is used to receive the commands from the Host
      --  Controller Driver (HCD)
      HCCOMMANDSTATUS    : aliased HCCOMMANDSTATUS_Register;
      --  Indicates the status on various events that cause hardware interrupts
      --  by setting the appropriate bits
      HCINTERRUPTSTATUS  : aliased HCINTERRUPTSTATUS_Register;
      --  Controls the bits in the HcInterruptStatus register and indicates
      --  which events will generate a hardware interrupt
      HCINTERRUPTENABLE  : aliased HCINTERRUPTENABLE_Register;
      --  The bits in this register are used to disable corresponding bits in
      --  the HCInterruptStatus register and in turn disable that event leading
      --  to hardware interrupt
      HCINTERRUPTDISABLE : aliased HCINTERRUPTDISABLE_Register;
      --  Contains the physical address of the host controller communication
      --  area
      HCHCCA             : aliased HCHCCA_Register;
      --  Contains the physical address of the current isochronous or interrupt
      --  endpoint descriptor
      HCPERIODCURRENTED  : aliased HCPERIODCURRENTED_Register;
      --  Contains the physical address of the first endpoint descriptor of the
      --  control list
      HCCONTROLHEADED    : aliased HCCONTROLHEADED_Register;
      --  Contains the physical address of the current endpoint descriptor of
      --  the control list
      HCCONTROLCURRENTED : aliased HCCONTROLCURRENTED_Register;
      --  Contains the physical address of the first endpoint descriptor of the
      --  bulk list
      HCBULKHEADED       : aliased HCBULKHEADED_Register;
      --  Contains the physical address of the current endpoint descriptor of
      --  the bulk list
      HCBULKCURRENTED    : aliased HCBULKCURRENTED_Register;
      --  Contains the physical address of the last transfer descriptor added
      --  to the 'Done' queue
      HCDONEHEAD         : aliased HCDONEHEAD_Register;
      --  Defines the bit time interval in a frame and the full speed maximum
      --  packet size which would not cause an overrun
      HCFMINTERVAL       : aliased HCFMINTERVAL_Register;
      --  A 14-bit counter showing the bit time remaining in the current frame
      HCFMREMAINING      : aliased HCFMREMAINING_Register;
      --  Contains a 16-bit counter and provides the timing reference among
      --  events happening in the HC and the HCD
      HCFMNUMBER         : aliased HCFMNUMBER_Register;
      --  Contains a programmable 14-bit value which determines the earliest
      --  time HC should start processing a periodic list
      HCPERIODICSTART    : aliased HCPERIODICSTART_Register;
      --  Contains 11-bit value which is used by the HC to determine whether to
      --  commit to transfer a maximum of 8-byte LS packet before EOF
      HCLSTHRESHOLD      : aliased HCLSTHRESHOLD_Register;
      --  First of the two registers which describes the characteristics of the
      --  root hub
      HCRHDESCRIPTORA    : aliased HCRHDESCRIPTORA_Register;
      --  Second of the two registers which describes the characteristics of
      --  the Root Hub
      HCRHDESCRIPTORB    : aliased HCRHDESCRIPTORB_Register;
      --  This register is divided into two parts
      HCRHSTATUS         : aliased HCRHSTATUS_Register;
      --  Controls and reports the port events on a per-port basis
      HCRHPORTSTATUS     : aliased HCRHPORTSTATUS_Register;
      --  Controls the port if it is attached to the host block or the device
      --  block
      PORTMODE           : aliased PORTMODE_Register;
   end record
     with Volatile;

   for USBFSH_Peripheral use record
      HCREVISION         at 16#0# range 0 .. 31;
      HCCONTROL          at 16#4# range 0 .. 31;
      HCCOMMANDSTATUS    at 16#8# range 0 .. 31;
      HCINTERRUPTSTATUS  at 16#C# range 0 .. 31;
      HCINTERRUPTENABLE  at 16#10# range 0 .. 31;
      HCINTERRUPTDISABLE at 16#14# range 0 .. 31;
      HCHCCA             at 16#18# range 0 .. 31;
      HCPERIODCURRENTED  at 16#1C# range 0 .. 31;
      HCCONTROLHEADED    at 16#20# range 0 .. 31;
      HCCONTROLCURRENTED at 16#24# range 0 .. 31;
      HCBULKHEADED       at 16#28# range 0 .. 31;
      HCBULKCURRENTED    at 16#2C# range 0 .. 31;
      HCDONEHEAD         at 16#30# range 0 .. 31;
      HCFMINTERVAL       at 16#34# range 0 .. 31;
      HCFMREMAINING      at 16#38# range 0 .. 31;
      HCFMNUMBER         at 16#3C# range 0 .. 31;
      HCPERIODICSTART    at 16#40# range 0 .. 31;
      HCLSTHRESHOLD      at 16#44# range 0 .. 31;
      HCRHDESCRIPTORA    at 16#48# range 0 .. 31;
      HCRHDESCRIPTORB    at 16#4C# range 0 .. 31;
      HCRHSTATUS         at 16#50# range 0 .. 31;
      HCRHPORTSTATUS     at 16#54# range 0 .. 31;
      PORTMODE           at 16#5C# range 0 .. 31;
   end record;

   --  USB0 Full-speed Host controller
   USBFSH_Periph : aliased USBFSH_Peripheral
     with Import, Address => System'To_Address (16#400A2000#);

end NXP_SVD.USBFSH;
